name: PR Pipeline - Validación del Pull Requests

on:
    push:
        branches: [ "main" ]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ "main" ]

permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Clonar el repo
              uses: actions/checkout@v3