name: PR Pipeline - Validación del Pull Requests

on:
    push:
        branches: [ "main" ]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [ "main" ]

permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Clonar el repo
              uses: actions/checkout@v3

    automerge:
        needs: build-and-test
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - name: Fusionar Pull Request
              uses: pascalgn/automerge-action@v0.16.2
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                MERGE_METHOD: "squash"